"""empty message

Revision ID: 4b2034f76020
Revises: 3b6f11730640
Create Date: 2023-01-17 19:15:05.223333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2034f76020'
down_revision = '3b6f11730640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planetID', sa.Integer(), nullable=False))
        batch_op.drop_column('PlanetID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PlanetID', sa.INTEGER(), server_default=sa.text('nextval(\'"planets_PlanetID_seq"\'::regclass)'), autoincrement=True, nullable=False))
        batch_op.drop_column('planetID')

    # ### end Alembic commands ###
